model:
  vision_model:
    variant: OpenGVLab/InternVL2-1B
    embed_dim: 512
    freeze: true
    _target_: models.models.encoder.vlm.VLMEncoderModel
  language_model:
    variant: OpenGVLab/InternVL2-1B
    lora: true
    lora_alpha: 64
    lora_r: 32
    lora_dropout: 0.1
    _target_: models.models.language_model.llm.LLM
  lr: 3.0e-05
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.999
  pct_start: 0.05
  speed_wps_mode: 2d
  predict_route_as_wps: true
  _target_: models.models.driving.DrivingModel
  rl_mode: false
data_module:
  base_dataset:
    data_path: database/dmw
    bucket_path: database/bucketsv2_dmw
    cut_bottom_quarter: true
    use_1d_wps: false
    use_commentary: false
    use_qa: false
    qa_augmentation: false
    commentary_augmentation: false
    use_old_towns: true
    use_only_old_towns: false
    use_town13: true
    skip_first_n_frames: 10
    pred_len: 11
    hist_len: 1
    hist_len_commentary: 5
    img_augmentation: false
    img_augmentation_prob: 0.5
    img_shift_augmentation: false
    img_shift_augmentation_prob: 0.5
    use_safety_flag: true
    num_route_points: 20
    route_as: target_point_command
    use_lmdrive_commands: false
  driving_dataset:
    _target_: models.dataloader.dataset_driving.Data_Driving
  batch_size: 8
  num_workers: 8
  train_partitions:
    all: 1.0
  train_partitions_dreamer:
    all: 1.0
  use_global_img: false
  _target_: models.dataloader.datamodule_human.DataModule  
seed: 42
gpus: 8
resume: false
resume_path: null
debug: false
overfit: 0
fp16_loss_scale: 32.0
enable_wandb: true
wandb_project: dmw
name: dmw
wandb_name: 'dmw'
max_epochs: 30
precision: 16-mixed
strategy: deepspeed_stage_2
val_every_n_epochs: 2
checkpoint: /checkpoints/epoch=013.ckpt/pytorch_model.pt